name: Main

on:
  push:
    branches:
      - main
      - master
      - Version-v*
      - trigger-ci*
      - benchmark-tests
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:

jobs:
  prep-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@main

      - run: yarn build:test

      - name: Upload artifact prep-build-test
        uses: actions/upload-artifact@v4
        with:
          name: prep-build-test
          path: ./dist/
          retention-days: 1

  prep-build-test-webpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@main

      - run: yarn webpack --test --no-lavamoat --no-cache --browser=chrome --lockdown --sentry --snow --env production
        env:
          SEGMENT_PROD_WRITE_KEY: '-' # A fake key just to make the build succeed

      - name: Upload artifact prep-build-test-webpack
        uses: actions/upload-artifact@v4
        with:
          name: prep-build-test-webpack
          path: ./dist/
          retention-days: 1

  run-pageload-benchmark:
    name: Run Benchmarks # So that the level 1 name will be "Run Benchmarks" in the GitHub Actions UI
    needs: prep-build-test
    uses: ./.github/workflows/benchmarks.yml
    with:
      name: run-pageload-benchmark # The level 2 name
      command: 'yarn benchmark:chrome --out test-artifacts/chrome/benchmark/pageload.json --retries 2'
      artifact: 'prep-build-test'

  run-user-actions-benchmark:
    name: Run Benchmarks # So that the level 1 name will be "Run Benchmarks" in the GitHub Actions UI
    needs: prep-build-test
    uses: ./.github/workflows/benchmarks.yml
    with:
      name: run-user-actions-benchmark # The level 2 name
      command: 'yarn user-actions-benchmark:chrome --out test-artifacts/chrome/benchmark/user_actions.json --retries 2'
      artifact: 'prep-build-test'

  run-pageload-benchmark-webpack:
    name: Run Benchmarks # So that the level 1 name will be "Run Benchmarks" in the GitHub Actions UI
    needs: prep-build-test-webpack
    uses: ./.github/workflows/benchmarks.yml
    with:
      name: run-pageload-benchmark-webpack # The level 2 name
      command: 'yarn benchmark:chrome --out test-artifacts/chrome/benchmark/pageload.json --retries 2'
      artifact: 'prep-build-test-webpack'

  run-user-actions-benchmark-webpack:
    name: Run Benchmarks # So that the level 1 name will be "Run Benchmarks" in the GitHub Actions UI
    needs: prep-build-test-webpack
    uses: ./.github/workflows/benchmarks.yml
    with:
      name: run-user-actions-benchmark-webpack # The level 2 name
      command: 'yarn user-actions-benchmark:chrome --out test-artifacts/chrome/benchmark/user_actions.json --retries 2'
      artifact: 'prep-build-test-webpack'
